### ISSUE TITLE
Support for the last version of gigantic?

### ISSUE THREAD

**Issue by Rong-Yao** [BigBoot/GiganticEmu#2]
Maybe that question have been asked before but are you planning to include support in arcsdk for the last arc version of gigantic?

**Comment by BigBoot** [comment]
In theory the retail version should be supported, you'd just need to patch out EAC (EAC isn't verified obviously, but the ancient version of it will BSOD any recent Windows 10, hooray for kernel mode anticheat). 
That said the retail version doesn't include the server component, so there would be no way to actually host any matches, which is why there isn't a lot of movement in this direction.

**Comment by Rong-Yao** [comment]
Yesterday I sat down doing exactly that but didn't yield much results. 
Anyhow, I thought that the last release still had p2p / lan supported for listen server, just dedicated server code was stripped away ... I might be wrong here.
My motivation to have the last release running was so I can find a way to fix few issues comparing some of the test game levels to the final release one along with the mechanics.

**Comment by BigBoot** [comment]
Afaik none of the retail versions ever had P2P support, in later versions there's the "custom game" thing were you can do 5v5 premades, but that was also using official servers, just without the matchmaking.

**Comment by Rong-Yao** [comment]
Well, I don't have experience with EAC or server emulation. X3 I can nop my way out of something or jump here and there, I do have experience with unreal engine, hence why I was wondering if its possible to make the new one running so I can retrofit from one another.

**Comment by BigBoot** [comment]
I don't have any experience with UE3, the biggest problem I see with "retrofitting from on to another" is that with the way UE3 works you get the engine code as well as the game code all mashed together into a single big mess + as far as I know the engine code was also heavily modified, though that's only something I heard.

**Comment by Rong-Yao** [comment]
Ye for me it's no issue fixing level maps and interface glitches as long as I can run the new one, exactly because of everything being mashed together I will need the game running, simply unpacking from the new and donating to the old won't just work. X) thankfully the code for loading custom maps and assets is still in the game so every issue the old one have is fixable with modding

**Comment by BigBoot** [comment]
Hmm, have you tried the latest steam or win10 versions, they should both work (well at least not crash your whole PC)

**Comment by Rong-Yao** [comment]
Steam version
* requires bypassing steam (thats easily achieved with many tools and tutorials of how steam stub works) and bypassing arc and uses EAC as well (it does require arc running, so same thing is the last arc version, so last steam and last arc version are identical, steam one just have the steam stub)

MS Store
* requires a license which can be dodged in offline mode, but that works only on accounts which had gigantic at some point added to the account, if the game was never added to an account now it just complains you don't have a license for this product, unsure if it requires arc running, but the game is cooked up differently from steam and arc versions.

Last Arc version
* it requires arc, it doesn't crash my pc on loading EAC (i have it installed because of a different game), but the game closes cuz i fail to bypass arc or i am missing some check in x64dbg

**Comment by BigBoot** [comment]
If only Arc is the only problem, you can just use this ArcSDK.dll:
[ArcSDK.zip](https://github.com/BigBoot/GiganticEmu/files/7194991/ArcSDK.zip)

**Comment by Rong-Yao** [comment]
Oke lan works on the last arc version, the problem is that when it switches to lan mode it awaits a response from the game server, a ping to see if the servers a still alive, if that fails it shoots, connection lost to the game server if we can give it a heartbeat then you can have other people joining on lan.
case1. Open a level, choose a character, works but nobody can connect
case2. Open a level, choose a character, open 127.0.0.1, it opens udp listen server, but it sending a ping every 15 seconds to the game server, if you simulate that ping... you can use the last version for matchmaking... i assume.
![image](https://user-images.githubusercontent.com/8936268/133987833-5751b932-79c7-47ae-8d23-cd513cc7d784.png)

**Comment by BigBoot** [comment]
That's outgoing connections, otherwise the state would be LISTENING right?
Especially with open being the command for connecting to a server, not for starting one...

**Comment by Rong-Yao** [comment]
The function is there serialize and linker have been removed from ipdrv.
i assume they couldn't remove the whole LAN code from UE, and just but online check on top, as far as i remember they were trying to keep the p2p because of custom games.
I will look into it.

**Comment by BigBoot** [comment]
I'm going to close this issue for now, as support for the latest/retail version is technically already there and I don't plan on expanding on it unless something changes about the match hosting.
