### ISSUE TITLE
Support for Throwback Event Build

### ISSUE THREAD

**Issue by NealSpellman** [BigBoot/GiganticEmu#7]
Figured I'd open this just in case there was interest in updating the ArcSDK dll, as it currently fails with "The procedure entry point ??1LobbyId@CC_SDK @ @ QEAA @ XZ could not be located in the dynamic link library".

The build doesn't allow console commands, but you can bind console commands to input to get around that or use the classic launch arguments option. Someone was posting pictures of multiple local clients in a local match, so I'm assuming it's got hosting capabilities.

EDIT: Confirmed hosting works, at least using the launch arguments. One client with the map and listener, then the other with the IP.

**Comment by BigBoot** [comment]
Support for hosting and joining games is now included with 48bb2ff, hosting requires patching some packages which can be done with the new GiganticEmu.ModdingToolkit and the included patches. The GiganticEmu.Mice and GiganticEmu.Web do not work with this build as the complete backend has been redone.
